name: django-py312
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - django
  - ipython
  - pillow
  - djangorestframework
  - django-filter
  - drf-spectacular
  - markdown
  - django-extensions
